version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.6
    commands:
      - echo "Installing Terraform..."
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
  build:
    commands:
      - echo "Planning Terraform..."
      - terraform plan
  post_build:
    commands:
      - echo "Applying Terraform..."
      - terraform apply -auto-approve

artifacts:
  files:
    - "**/*"
