version: 0.2

phases:
  install:
    runtime-versions:
      python: latest  # You can leave this or remove it
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
      - unzip terraform_1.8.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Planning Terraform changes..."
      - terraform plan

  post_build:
    commands:
      - echo "Applying Terraform configuration..."
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
