version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -O https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip
      - unzip terraform_1.8.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
  build:
    commands:
      - echo "Destroying infrastructure..."
      - terraform destroy -auto-approve
