version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Terraform...
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init

  build:
    commands:
      - echo Applying infrastructure...
      - terraform apply -auto-approve
      - echo Sleeping 30 seconds for any async setup...
      - sleep 30
      - echo Destroying infrastructure...
      - terraform destroy -auto-approve

artifacts:
  files:
    - '**/*'
